name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is required for Trusted Publishing
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build distributions
      run: |
        uv build --package identa-core
        uv build --package identa-sdk

    - name: Publish identa-core to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: packages/identa-core/dist/

    - name: Publish identa-sdk to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: packages/identa-sdk/dist/
